name: Deploy publish-deploy
on: [push]
jobs: 
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script: |
            cd /data
            sudo rm -rf monitor-web
            git clone git@github.com:yeshaojun/monitor-web.git
            cd monitor-web
            npm install
            npm run build
