name: Deploy publish-deploy
on: [push]
jobs: 
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: 119.45.209.87
          username: ubuntu
          password: ${{ secrets.SSH_PDW }}
          script: whoami